name: ci-cd-pipeline
on: 
    push:
        branches: 
            - main
env:
    DOCKER_USERNAME: uday0710
jobs:
    frontend-docker-build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: log in to docker hub
            uses: docker/login-action@v3
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: set up docker buildx
            uses: docker/setup-buildx-action@v3
          - name: build and push docker image
            uses: docker/build-push-action@v6
            with:
              file: ./frontend/Dockerfile
              context: ./frontend
              push: true
              tags: ${{env.DOCKER_USERNAME}}/frontend-react:latest
    
    frontend-kubernetes-deploy:
        runs-on: aws-ec2-runner
        needs: frontend-docker-build
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: docker-container
            run: |
              docker run --name frontend-react -d -p 8085:80 frontend-react:latest
          # - name: Create kind cluster
          #   uses: helm/kind-action@v1
          #   with:
          #     cluster_name: kind-cluster
          # - name: Install Helm
          #   uses: azure/setup-helm@v4
          # - name: deploy helm chart
          #   run: |
          #     helm upgrade \
          #     --install \
          #     frontend-release \
          #     ./kubernetes/frontend \

