name: ci-cd-pipeline
on: 
    push:
        branches: 
            - main
jobs:
    mysql-deploy:
        runs-on: aws-ec2-runner
        steps:
          - name: docker-container
            run: |
              docker run --name mysqldb --network my-network -d mysql:latest