name: mysql-workflow
on: 
    push:
        branches: 
            - main
env:
    DOCKER_USERNAME: uday0710
jobs:
    mysql-deploy:
        runs-on: local-runner
        steps:
          - name: create docker network
            run: |
                docker network create my-network
          - name: docker-container
            run: |
              docker run --name mysqldb --network my-network -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
    
    backend-docker-build:
        runs-on: ubuntu-latest
        needs: mysql-deploy
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: log in to docker hub
            uses: docker/login-action@v3
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: set up docker buildx
            uses: docker/setup-buildx-action@v3
          - name: build and push docker image
            uses: docker/build-push-action@v6
            with:
              file: ./backend/Dockerfile
              context: ./backend
              push: true
              tags: ${{env.DOCKER_USERNAME}}/backend-node:latest
    
    backend-kubernetes-deploy:
        runs-on: local-runner
        needs: backend-docker-build
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: docker-container
            run: |
              docker run --name backend-node --network my-network -d -p 8085:80 uday0710/backend-node:latest
            
    frontend-docker-build:
        runs-on: ubuntu-latest
        needs: backend-kubernetes-deploy
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: log in to docker hub
            uses: docker/login-action@v3
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: set up docker buildx
            uses: docker/setup-buildx-action@v3
          - name: build and push docker image
            uses: docker/build-push-action@v6
            with:
              file: ./frontend/Dockerfile
              context: ./frontend
              push: true
              tags: ${{env.DOCKER_USERNAME}}/frontend-react:latest
    
    frontend-kubernetes-deploy:
        runs-on: local-runner
        needs: frontend-docker-build
        steps:
          - name: checkout
            uses: actions/checkout@v4
          - name: docker-container
            run: |
              docker run --name frontend-react --network my-network -d -p 8084:80 uday0710/frontend-react:latest